services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    restart: unless-stopped